/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import elecciones.Circunscripcion;
import elecciones.Eleccion;
import elecciones.FormacionPolitica;
import elecciones.Lista;
import elecciones.Militante;
import elecciones.PartidoPolitico;
import elecciones.Votantes;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Vista extends javax.swing.JFrame {

    ArrayList <Circunscripcion> circunscripciones = new ArrayList<>();
    ArrayList <FormacionPolitica> formaciones = new ArrayList<>();
    ArrayList <Militante> militantes = new ArrayList<>();
    ArrayList <Votantes> votantes = new ArrayList<>();
    Eleccion eleccion;
    ArrayList<Eleccion> historico = new ArrayList<Eleccion>();
    boolean votosManuales = false;
    
    
    
     
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelMilitantes = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cargarTexto = new javax.swing.JTextArea();
        panel_nuevosdatos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablaCircunscripciones = new javax.swing.JTable();
        boton_addCircunscripcion = new javax.swing.JButton();
        boton_addPartido = new javax.swing.JButton();
        jTextFieldNombreCircuns = new javax.swing.JTextField();
        jTextFieldPoblacionCircuns = new javax.swing.JTextField();
        jTextFieldParticipacionCircuns = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableCircuns = new javax.swing.JTable();
        jPanelPartidos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombrePP = new javax.swing.JTextField();
        jTextFieldSiglasPP = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextFieldLogoPP = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVotantes = new javax.swing.JTable();
        boton_crearpartido = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableMilitantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setToolTipText("");

        jButton1.setText("DATOS");

        jButton2.setText("ELECCIONES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton3.setText("Cargar datos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cargarTexto.setColumns(20);
        cargarTexto.setRows(5);
        cargarTexto.setName("cargarTexto"); // NOI18N
        jScrollPane1.setViewportView(cargarTexto);
        cargarTexto.getAccessibleContext().setAccessibleName("cargarTexto");
        cargarTexto.getAccessibleContext().setAccessibleDescription("cargarTexto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 484, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelMilitantes.addTab("Cargar", jPanel3);

        jTablaCircunscripciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Siglas", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(jTablaCircunscripciones);

        boton_addCircunscripcion.setText("Añadir Circunscripcion");
        boton_addCircunscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_addCircunscripcionActionPerformed(evt);
            }
        });

        boton_addPartido.setText("Añadir Partidos");
        boton_addPartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_addPartidoActionPerformed(evt);
            }
        });

        jTextFieldNombreCircuns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCircunsActionPerformed(evt);
            }
        });

        jLabel11.setText("Nombre");

        jLabel12.setText("Poblacion");

        jLabel13.setText("Participacion");

        jTableCircuns.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Poblacion", "Participacion"
            }
        ));
        jScrollPane5.setViewportView(jTableCircuns);

        javax.swing.GroupLayout panel_nuevosdatosLayout = new javax.swing.GroupLayout(panel_nuevosdatos);
        panel_nuevosdatos.setLayout(panel_nuevosdatosLayout);
        panel_nuevosdatosLayout.setHorizontalGroup(
            panel_nuevosdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nuevosdatosLayout.createSequentialGroup()
                .addGroup(panel_nuevosdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_nuevosdatosLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(panel_nuevosdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(63, 63, 63)
                        .addGroup(panel_nuevosdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton_addCircunscripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(boton_addPartido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombreCircuns)
                            .addComponent(jTextFieldPoblacionCircuns)
                            .addComponent(jTextFieldParticipacionCircuns))
                        .addGap(0, 288, Short.MAX_VALUE))
                    .addGroup(panel_nuevosdatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_nuevosdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        panel_nuevosdatosLayout.setVerticalGroup(
            panel_nuevosdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nuevosdatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boton_addPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(panel_nuevosdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreCircuns, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_nuevosdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPoblacionCircuns, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_nuevosdatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldParticipacionCircuns, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_addCircunscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanelMilitantes.addTab("Nuevos datos", panel_nuevosdatos);

        jLabel1.setText("Nombre");

        jLabel2.setText("Siglas");

        jLabel3.setText("Logo");

        jLabel4.setText("Secretario");

        jTextFieldNombrePP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombrePPActionPerformed(evt);
            }
        });

        jButton4.setText("Añadir votantes");

        jButton5.setText("Añadir Simpatizantes");

        jButton6.setText("Añadir militantes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTableVotantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Edad", "Profesion"
            }
        ));
        jScrollPane3.setViewportView(jTableVotantes);

        boton_crearpartido.setText("Añadir Partido");
        boton_crearpartido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crearpartidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPartidosLayout = new javax.swing.GroupLayout(jPanelPartidos);
        jPanelPartidos.setLayout(jPanelPartidosLayout);
        jPanelPartidosLayout.setHorizontalGroup(
            jPanelPartidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPartidosLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanelPartidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPartidosLayout.createSequentialGroup()
                        .addGroup(jPanelPartidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPartidosLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldNombrePP, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPartidosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldSiglasPP, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(jPanelPartidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addGroup(jPanelPartidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldLogoPP, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPartidosLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPartidosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanelPartidosLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(boton_crearpartido, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPartidosLayout.setVerticalGroup(
            jPanelPartidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPartidosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanelPartidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombrePP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogoPP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanelPartidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSiglasPP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanelPartidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(boton_crearpartido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jPanelMilitantes.addTab("Crear partidos", jPanelPartidos);

        jLabel5.setText("Nombre");

        jLabel6.setText("Apellidos");

        jLabel7.setText("Edad");

        jLabel8.setText("Profesion");

        jLabel9.setText("Carnet");

        jLabel10.setText("Cuota");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton7.setText("Crear nuevo");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Cargar militantes");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTableMilitantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Edad", "Profesion", "Tipo"
            }
        ));
        jScrollPane4.setViewportView(jTableMilitantes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel9))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextField2))))
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                            .addComponent(jTextField7)))
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(411, 411, 411)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))))
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelMilitantes.addTab("Militantes", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelMilitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelMilitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // Si ya hay una eleccion creada, advertimos de la pérdida de datos.
        if(historico.size()>=1){
            int n = JOptionPane.showConfirmDialog(
                TabBienvenido,
                "ADVERTENCIA: Si cargas una elección borraras los datos \nde la elección actual. ¿Deseas continuar?",
                "PELIGRO PELIGRO PELIGRO",
                JOptionPane.YES_NO_OPTION);
            if(n!=0){
                // Si no dice que quiere continuar, nos vamos
                cargarTexto.append("\nCarga de elección cancelada por el usuario");
                return;
            } else {
                cargarTexto.append("\nForzando la carga de elección desde disco, se eliminarán los datos actuales");
            }
        }

        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(TabBienvenido);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            cargarTexto.append("\nArchivo elegido: " + chooser.getSelectedFile().getName());
            File archivo = chooser.getSelectedFile();

            try{
                try (ObjectInputStream entrada = new ObjectInputStream(new FileInputStream(archivo))) {
                    historico = (ArrayList<Eleccion>) entrada.readObject();
                }
                // actualizarTablaHistorico();
            } catch (IOException e){
                cargarTexto.append("\nHa ocurrido un error al intentar abrir el archivo: "+e.getLocalizedMessage());

            } catch (ClassNotFoundException e){
                cargarTexto.append("\nClase no válida (¿Archivo corrupto?)");

            } catch(ClassCastException e){
                cargarTexto.append("\nEl archivo no era una elección válida (¿Archivo corrupto?)");
            } catch(Exception e){
                e.printStackTrace();
                cargarTexto.append("\nError indefinido al intentar abrir el archivo");
                cargarTexto.append(e.getMessage());
                cargarTexto.append(e.toString());
            }

        } else {
            cargarTexto.append("Operacion cancelada por el usuario.");

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void boton_addCircunscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_addCircunscripcionActionPerformed
      if(formaciones.size()<2){
            JOptionPane.showMessageDialog(jFrame2, "Debe haber al menos dos formaciones políticas para poder hacer elecciones",
                    "Datos insuficientes", JOptionPane.WARNING_MESSAGE);
        } else if(jTextFieldNombreCircuns.getText().equals("")||
                    jTextFieldPoblacionCircuns.getText().equals("")||
                    jTextFieldParticipacionCircuns.getText().equals("")){
            JOptionPane.showMessageDialog(jFrame2, "Todos los campos son obligatorios",
                    "Datos insuficientes", JOptionPane.WARNING_MESSAGE);            
        } else {
            try {
                double participacion = Double.parseDouble(jTextFieldParticipacionCircuns.getText());
                if(participacion>1||participacion<=0) throw new IllegalArgumentException();
                // Crea el partido político
                Circunscripcion circunscripcion = new Circunscripcion(
                        jTextFieldNombreCircuns.getText(),
                        Integer.parseInt(jTextFieldPoblacionCircuns.getText()),
                        participacion
                );

                // Asignamos las formaciones creadas anteriormente a la circunscripcion
                circunscripcion.setFormaciones(formaciones);
                
                    for(FormacionPolitica f: formaciones){
                        
                        ArrayList<Militante> temporal = new ArrayList<>();
                       
                            for (int i = 0; i < circunscripcion.getEscaños(); i++) {
                                temporal.add(f.getMilitantes().get(i));
                            }
                            
                            
                                circunscripcion.getListasPartidos().add(new Lista(
                                        temporal,
                                        f,
                                        circunscripcion.getNombre(),
                                        f.getNombre()+" "+circunscripcion.getNombre()
                                ));
                    }  



         

                        // Creamos un nuevo conjunto temporal de partidos
                        formaciones = new ArrayList<>();
                        
                        
                        
                       DefaultTableModel dm = (DefaultTableModel) jTablaCircunscripciones.getModel();
                        int rowCount = dm.getRowCount();
                     //Remove rows one by one from the end of the table
                      for (int i = rowCount - 1; i >= 0; i--) {
                         dm.removeRow(i);
                   }
                    
                        

                        // Añadimos la circunscripcion creada a la tabla en elecciones
                        DefaultTableModel modeloCircunscripcion = (DefaultTableModel) jTableCircuns.getModel();
                        modeloCircunscripcion.addRow(new Object[]{
                                jTextFieldNombreCircuns.getText(),
                                Integer.parseInt(jTextFieldPoblacionCircuns.getText()),
                                participacion,
                                circunscripcion.getEscaños()
                        });

                        // Añadimos la circunscripcion creada a la lista temporal de circunscripciones
                        circunscripciones.add(circunscripcion);
//                        historico.get(jTableHistorico.getSelectedRow()).setEleccionesEnCircunscripcion(circunscripciones);

                        // Resetamos todos los campos del formulario
                        jTextFieldNombreCircuns.setText("");
                        jTextFieldPoblacionCircuns.setText("");
                        jTextFieldParticipacionCircuns.setText("");

                        // Resetamos la tabla
                       // DefaultTableModel modeloPart = (DefaultTableModel) jTablePP.getModel();
                       // modeloPart.setRowCount(0);

                        // Cerramos la ventana
                        // TODO add your handling code here:

                        jButton3.setEnabled(true);
                    

            } catch (NumberFormatException e){
                /* JOptionPane.showMessageDialog(jFrame3, "Introduce numeros validos porfavor",
                    "Datos no válidos", JOptionPane.ERROR_MESSAGE);*/
            } catch (IllegalArgumentException e){
                /* //JOptionPane.showMessageDialog(jFrame3, "La participación debe ser mayor a 0 y menor o igual a 1",
                    "Datos no válidos", JOptionPane.ERROR_MESSAGE);*/
            } catch (IndexOutOfBoundsException e){
                            JOptionPane.showMessageDialog(jFrame2, "No hay suficientes militantes para rellenar la lista de algún partido",
                            "Datos insuficientes", JOptionPane.WARNING_MESSAGE);
                        }
        }
                                                      

    }//GEN-LAST:event_boton_addCircunscripcionActionPerformed

    private void boton_addPartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_addPartidoActionPerformed
      
      
         jPanelMilitantes.setSelectedIndex(2);
    }//GEN-LAST:event_boton_addPartidoActionPerformed

    private void jTextFieldNombrePPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombrePPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombrePPActionPerformed

    private void boton_crearpartidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crearpartidoActionPerformed
           if(militantes==null||votantes==null||militantes.size()<2){
            JOptionPane.showMessageDialog(jFrame3, "Por favor, introduce al menos 2 Militantes y 1 Simpatizante",
                    "Datos insuficientes", JOptionPane.WARNING_MESSAGE);
        } else if(jTextFieldNombrePP.getText().equals("")||
                jTextFieldSiglasPP.getText().equals("")||
                jTextFieldLogoPP.getText().equals("")){
            JOptionPane.showMessageDialog(jFrame3, "Todos los campos son obligatorios",
                    "Campos no válidos", JOptionPane.ERROR_MESSAGE);
        } else {
            // Crea el partido político
            PartidoPolitico partido = new PartidoPolitico(
                    jTextFieldNombrePP.getText(),
                    jTextFieldSiglasPP.getText(),
                    jTextFieldLogoPP.getText()
            );

            // Setea el campo Siglas de todos los votantes
            for(Votantes vot:votantes){
                vot.setSiglasPartido(jTextFieldSiglasPP.getText());
            }

            // Asignamos los objetos temporales militantes y votantes creados hasta ahora al partido
            partido.setMilitantes(militantes);
            partido.setVotantes(votantes);
        
            
            // Creamos un nuevo conjunto vacío de militantes y votantes temporal
            militantes = new ArrayList<>();
            votantes = new ArrayList<>();

            DefaultTableModel dm = (DefaultTableModel) jTableVotantes.getModel();
            int rowCount = dm.getRowCount();
         //Remove rows one by one from the end of the table
         for (int i = rowCount - 1; i >= 0; i--) {
         dm.removeRow(i);
            }
            
            
            
            
            // Añadimos el partido creado a la tabla de formaciones en circunscripciones
            DefaultTableModel modeloPartidos = (DefaultTableModel) jTablaCircunscripciones.getModel();
            modeloPartidos.addRow(new Object[]{
                    jTextFieldNombrePP.getText(),
                    jTextFieldSiglasPP.getText(),
                    "Partido"
            });

            // Añadimos el partido a la lista temporal de formaciones.
            formaciones.add(partido);

            // Resetamos todos los campos del formulario
            jTextFieldNombrePP.setText("");
            jTextFieldSiglasPP.setText("");
            jTextFieldLogoPP.setText("");

            // Resetamos la tabla
           // DefaultTableModel modeloVot = (DefaultTableModel) jTableVotantesPP.getModel();
           // modeloVot.setRowCount(0);

            // Cerramos la ventana
          //  jPanelPartidos.
          
           jPanelMilitantes.setSelectedIndex(1);
        }   
    }//GEN-LAST:event_boton_crearpartidoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        int opcion = fileChooser.showOpenDialog(jFrame3); //Se abre la ventana para seleccionar archivo a cargar.
        if (opcion == JFileChooser.APPROVE_OPTION){
            // Creamos un String con la ruta del archivo seleccionado
            String archivo = fileChooser.getSelectedFile().getPath(); 
            // Intentamos abrirlo
            try{
                BufferedReader inFile = new BufferedReader (new FileReader(archivo));
                String inputLine;
                
                while ((inputLine = inFile.readLine())!=null){
                    String[] atrmil = inputLine.split(";");
                    // Igual que con los campos, añadimos a la lista un nuevo militantes
                    // con las propiedades del txt
                    Militante mil = new Militante(
                            atrmil[0],                      // Nombre
                            Integer.parseInt(atrmil[1]),    // Edad
                            atrmil[2],                      // Profesión
                            atrmil[3],                      // Género
                            atrmil[4],                      // Cuota
                            atrmil[5]                       // Carnet
                    );
                    militantes.add(mil);
                    votantes.add(mil);
                    
                    // Lo añadimos a la tabla
                    DefaultTableModel modelo = (DefaultTableModel) jTableVotantes.getModel();
                    modelo.addRow(new Object[]{
                        atrmil[0],
                        Integer.parseInt(atrmil[1]),
                        atrmil[2],
                        "Militante"
                    });
                }
                
            } catch(FileNotFoundException e){
            } catch (IOException ex) {
               // Logger.getLogger(Igelec.class.getName()).log(Level.SEVERE, null, ex);
                
            } catch (ArrayIndexOutOfBoundsException e2){
                System.out.println("Los datos del fichero no son validos");

            }
            
        }
        
          jPanelMilitantes.setSelectedIndex(2);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextFieldNombreCircunsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCircunsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCircunsActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
      jPanelMilitantes.setSelectedIndex(3);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }
    
    
    
    
    
    
    
     
    
    
     private JFrame jFrame3 = new JFrame();
     private javax.swing.JFrame jFrame2;
     
     
  private javax.swing.JPanel TabBienvenido;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_addCircunscripcion;
    private javax.swing.JButton boton_addPartido;
    private javax.swing.JButton boton_crearpartido;
    private javax.swing.JTextArea cargarTexto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jPanelMilitantes;
    private javax.swing.JPanel jPanelPartidos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTablaCircunscripciones;
    private javax.swing.JTable jTableCircuns;
    private javax.swing.JTable jTableMilitantes;
    private javax.swing.JTable jTableVotantes;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextFieldLogoPP;
    private javax.swing.JTextField jTextFieldNombreCircuns;
    private javax.swing.JTextField jTextFieldNombrePP;
    private javax.swing.JTextField jTextFieldParticipacionCircuns;
    private javax.swing.JTextField jTextFieldPoblacionCircuns;
    private javax.swing.JTextField jTextFieldSiglasPP;
    private javax.swing.JPanel panel_nuevosdatos;
    // End of variables declaration//GEN-END:variables

   


}
